application: its-hackademic
version: 4-0-0
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /favicon.ico
  static_files: dist/static/favicon.ico
  upload: dist/static/favicon.ico

- url: /manifest.json
  static_files: dist/static/manifest.json
  upload: dist/static/manifest.json

- url: /sw-import.js
  static_files: dist/static/sw-import.js
  upload: dist/static/sw-import.js

- url: /bootstrap
  static_dir: dist/static/bower_components/platinum-sw/bootstrap

- url: /sw-toolbox
  static_dir: dist/static/bower_components/sw-toolbox

- url: /cache-config.json
  static_files: dist/static/cache-config.json
  upload: dist/static/cache-config.json

- url: /scripts
  static_dir: dist/static/scripts

- url: /styles
  static_dir: dist/static/styles

- url: /bower_components
  static_dir: dist/static/bower_components

- url: /elements
  static_dir: dist/static/elements

- url: /images
  static_dir: dist/static/images

- url: /code-of-conduct.html
  static_files: dist/static/code-of-conduct.html
  upload: dist/static/code-of-conduct.html

- url: .*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?bower\.json
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^(.*/)?tests/.*
- ^.*.md|markdown
